# Generated by Django 4.2.2 on 2023-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_socialmedia_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='app',
            field=models.CharField(choices=[('insta', 'Instagram')], max_length=100),
        ),
    ]
