# Generated by Django 4.2.2 on 2023-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_socialmedia_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='app',
            field=models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook')], max_length=110),
        ),
    ]
