# Generated by Django 4.2.2 on 2023-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='app',
            field=models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('tiktok', 'Tiktok'), ('wp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('twitter', 'Twitter')], max_length=110),
        ),
    ]
