# Generated by Django 4.2.2 on 2023-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_home_homecontact_about_text_az_about_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='text_az',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='text_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='text_az',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='text_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='title_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homecontact',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
