# Generated by Django 4.2.2 on 2023-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_home_text_az_home_text_ru_home_title_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_count', models.IntegerField()),
                ('worldwide_count', models.IntegerField()),
                ('worker_count', models.IntegerField()),
                ('winner_count', models.IntegerField()),
            ],
        ),
    ]
