# Generated by Django 4.2.2 on 2023-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_funfact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funfact',
            old_name='project_count',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='funfact',
            name='winner_count',
        ),
        migrations.RemoveField(
            model_name='funfact',
            name='worker_count',
        ),
        migrations.RemoveField(
            model_name='funfact',
            name='worldwide_count',
        ),
        migrations.AddField(
            model_name='funfact',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
