# Generated by Django 4.2.2 on 2023-06-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_backgroundimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_ru',
        ),
    ]
