# Generated by Django 4.2.2 on 2023-06-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_blog_slug_az_remove_blog_slug_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='about',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='blogs',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='contact',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='products',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='main',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
